### ISSUE TITLE
master branch missing

### ISSUE THREAD

**Issue by floion** [embeddedarm/u-boot#3]
Hi guys,
when and why has the master branch been deleted? Was it by mistake?

**Comment by markfeathers** [comment]
We added a new branch based on a much more recent u-boot and didn't want to keep the older name for master which was not clear it was this older release.  I didn't realize anyone was automatically pulling this down, but from how fast you found this I'm assuming you were relying on this.  This was changed late yesterday.  Sorry about that.  Can you change to pull from the v2014.10 branch instead?  This will not change again in the future.

**Comment by floion** [comment]
Hi Mark, thanks for the quick reply. Will switch over to v2014.10
